services:
  auth:
    build:
      context: .
    container_name: auth-service
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: auth-db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - auth-main

  auth-db:
    image: postgres:17
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - auth-main


volumes:
  auth-db-data:

networks:
  auth-main:
